### ISSUE TITLE
Bee.cpp line 150 sizeof return

### ISSUE THREAD

**Issue by BDK-FPE** [kmark/Bee#4]
On line 150 of Bee.cpp:

for(int i = 0; i < sizeof packet; i++) throws a compiler warning because sizeof returns a std::size_t which is of type unsigned integer.

Propose changing the declaration in the for loop to type uint16_t:

for(uint16_t i = 0; i < sizeof packet; i++)

**Comment by kmark** [comment]
This can be removed entirely since it's just there for a commented-out print/debug statement.
